//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpchainWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ungcuvien
    {
        public long ma_ungcuvien { get; set; }
        public string sHoten { get; set; }
        public Nullable<bool> bGioitinh { get; set; }
        public Nullable<System.DateTime> dNgaysinh { get; set; }
        public string sEmail { get; set; }
        public string sDiachi { get; set; }
        public Nullable<long> ma_dotbaucu { get; set; }
        public string sGhichu { get; set; }
    }
}
