//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpchainWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_signature
    {
        public int id { get; set; }
        public string block_hash { get; set; }
        public Nullable<int> ma_cutri { get; set; }
        public Nullable<int> ma_dotbaucu { get; set; }
        public string public_key { get; set; }
        public string cypher_private_key1 { get; set; }
    }
}
