//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpchainWebAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class admin_vote : DbContext
    {
        public admin_vote()
            : base("name=admin_vote")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_cutri> tbl_cutri { get; set; }
        public virtual DbSet<tbl_dotbaucu> tbl_dotbaucu { get; set; }
        public virtual DbSet<tbl_taikhoan> tbl_taikhoan { get; set; }
    
        public virtual int sp_checklogin(string sTendangnhap, string sMatKhau, ObjectParameter ma_taikhoan, ObjectParameter ma_quyen)
        {
            var sTendangnhapParameter = sTendangnhap != null ?
                new ObjectParameter("sTendangnhap", sTendangnhap) :
                new ObjectParameter("sTendangnhap", typeof(string));
    
            var sMatKhauParameter = sMatKhau != null ?
                new ObjectParameter("sMatKhau", sMatKhau) :
                new ObjectParameter("sMatKhau", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_checklogin", sTendangnhapParameter, sMatKhauParameter, ma_taikhoan, ma_quyen);
        }
    }
}
