

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CSharpchainWebAPI
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class admin_voteEntities : DbContext
{
    public admin_voteEntities()
        : base("name=admin_voteEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<tbl_cutri> tbl_cutri { get; set; }

    public virtual DbSet<tbl_taikhoan> tbl_taikhoan { get; set; }

    public virtual DbSet<tbl_dotbaucu> tbl_dotbaucu { get; set; }

    public virtual DbSet<dm_trangthai_dotbaucu> dm_trangthai_dotbaucu { get; set; }

}

}

