
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CSharpchainWebAPI
{

using System;
    using System.Collections.Generic;
    
public partial class dm_dauphieu
{

    public string ma_dauphieu { get; set; }

    public string ten_dauphieu { get; set; }

    public string icon { get; set; }

    public string type { get; set; }

}

}
