
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CSharpchainWebAPI
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_dotbaucu
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbl_dotbaucu()
    {

        this.tbl_cutri = new HashSet<tbl_cutri>();

    }


    public long ma_dot { get; set; }

    public string sTendot { get; set; }

    public Nullable<System.DateTime> dThoigianbd { get; set; }

    public Nullable<System.DateTime> dThoigiankt { get; set; }

    public string sGhichu { get; set; }

    public string sNoiDung { get; set; }

    public Nullable<int> iTrangThai { get; set; }

    public string sHinhThuc { get; set; }

    public string sSoPhieu { get; set; }

    public Nullable<int> iNguoiTao { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbl_cutri> tbl_cutri { get; set; }

}

}
