
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CSharpchainWebAPI
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_cutri
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbl_cutri()
    {

        this.tbl_dotbaucu = new HashSet<tbl_dotbaucu>();

    }


    public long ma_cutri { get; set; }

    public string sHoten { get; set; }

    public Nullable<bool> bGioitinh { get; set; }

    public Nullable<System.DateTime> dNgaysinh { get; set; }

    public string sEmail { get; set; }

    public string sDiachi { get; set; }

    public Nullable<long> ma_dotbaucu { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbl_dotbaucu> tbl_dotbaucu { get; set; }

}

}
