
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CSharpchainWebAPI
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_taikhoan
{

    public long ma_taikhoan { get; set; }

    public string sHovaten { get; set; }

    public string sTendangnhap { get; set; }

    public string sMatkhau { get; set; }

    public Nullable<System.DateTime> dNgaysinh { get; set; }

    public Nullable<bool> bGgioitinh { get; set; }

    public string sEmail { get; set; }

    public string sSdt { get; set; }

    public string sDiachi { get; set; }

    public Nullable<bool> iTrangthai { get; set; }

    public Nullable<int> ma_quyen { get; set; }

    public Nullable<int> ma_xacthuc { get; set; }

}

}
